from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Mapping, Sequence

import numpy as np
import pandas as pd

from .dynamics import require_columns


@dataclass(frozen=True)
class BranchSummaryArtifacts:
    """Collection of the five validated Figure 5 derived tables."""

    transition_table: pd.DataFrame
    ecology_summary: pd.DataFrame
    program_summary: pd.DataFrame
    escape_risk_summary: pd.DataFrame
    stats_summary: pd.DataFrame


@dataclass(frozen=True)
class ThresholdSensitivityArtifacts:
    """Tables and text generated by a branch-threshold sensitivity sweep."""

    projected_table: pd.DataFrame
    counts_by_timepoint: pd.DataFrame
    transition_summary: pd.DataFrame
    patient_table: pd.DataFrame
    switch_rates: pd.DataFrame
    summary_text: str


@dataclass(frozen=True)
class ThresholdBranchSpec:
    """Schema for threshold-dependent nearest-branch projection."""

    sample_column: str = "sample"
    patient_column: str = "Patient_ID"
    sample_id_column: str = "sample_id"
    timepoint_column: str = "timepoint"
    time_index_column: str = "time_index"
    malignant_cells_column: str = "malignant_cells"
    projection_eligible_column: str = "projection_eligible"
    branch_distance_columns: tuple[str, ...] = (
        "dist_B1",
        "dist_B2",
        "dist_B3",
    )
    branch_labels: tuple[str, ...] = ("B1", "B2", "B3")
    state_columns: tuple[str, ...] = (
        "ilr_stem_vs_committed",
        "ilr_prog_vs_mature",
        "ilr_gmp_vs_monodc",
        "T_NK_given_known_z",
        "Myeloid_APC_given_known_z",
        "B_Plasma_given_known_z",
    )
    metadata_columns: tuple[str, ...] = (
        "Biopsy_Origin",
        "Subgroup",
        "Treatment_Outcome",
    )
    diagnosis_timepoint: str = "DX"
    relapse_timepoint: str = "REL"
    remission_timepoint: str = "REM"

    def __post_init__(self) -> None:
        if len(self.branch_distance_columns) != len(self.branch_labels):
            raise ValueError(
                "branch_distance_columns and branch_labels must have equal length."
            )
        if not self.branch_labels:
            raise ValueError("At least one branch label is required.")
        if len(set(self.branch_labels)) != len(self.branch_labels):
            raise ValueError("branch_labels must be unique.")
        if len(set(self.branch_distance_columns)) != len(
            self.branch_distance_columns
        ):
            raise ValueError("branch_distance_columns must be unique.")


# ---------------------------------------------------------------------------
# Shared helpers
# ---------------------------------------------------------------------------


def zscore_series(series: pd.Series) -> pd.Series:
    """Population-standard-deviation z-score with zero-variance protection."""
    numeric = pd.to_numeric(series, errors="coerce")
    mean = np.nanmean(numeric)
    standard_deviation = np.nanstd(numeric, ddof=0)
    if not np.isfinite(standard_deviation) or standard_deviation == 0:
        return pd.Series(np.zeros(len(numeric)), index=series.index, dtype=float)
    return (numeric - mean) / standard_deviation


def safe_mode(series: pd.Series, *, default: str = "Unknown") -> str:
    """Most frequent non-missing string, preserving pandas tie behavior."""
    values = series.dropna().astype(str)
    if values.empty:
        return default
    return str(values.value_counts().idxmax())


def sort_by_declared_order(
    table: pd.DataFrame,
    column: str,
    order: Sequence[str],
) -> pd.DataFrame:
    """Sort a label column by a declared order, then alphabetically."""
    output = table.copy()
    order_map = {str(label): index for index, label in enumerate(order)}
    output["_branch_order"] = (
        output[column].astype(str).map(order_map).fillna(999)
    )
    return output.sort_values(["_branch_order", column]).drop(
        columns="_branch_order"
    )


def first_nonmissing(series: pd.Series) -> Any:
    """Return the first non-missing value or ``pd.NA``."""
    values = series.dropna()
    return values.iloc[0] if len(values) > 0 else pd.NA


# ---------------------------------------------------------------------------
# Frozen-scaffold basin summaries (Figure 5 layer)
# ---------------------------------------------------------------------------


def build_branch_transition_table(
    interval_table: pd.DataFrame,
    jump_table: pd.DataFrame,
    sample_table: pd.DataFrame,
    *,
    scaffold_columns: Sequence[str],
    interval_value: str = "DX_to_REL",
) -> pd.DataFrame:
    """Annotate row-level start-to-end branch transitions.

    The join keys and output names reproduce the validated pediatric-leukemia
    Figure 5 implementation.
    """
    scaffold_columns = tuple(str(column) for column in scaffold_columns)
    require_columns(
        interval_table,
        [
            "patient_id",
            "interval_class",
            "sample_start",
            "sample_end",
            "branch_start",
            "branch_end",
            "branch_switch",
            "displacement_hd",
        ],
        context="Interval table",
    )
    require_columns(
        jump_table,
        ["patient_id", "sample_start", "sample_end", "jump_score"],
        context="Jump-candidate table",
    )
    sample_columns = [
        "sample_id",
        "clinical_timepoint_coarse",
        "branch_id_dominant",
        "ecotype_label",
        "theta_eff",
        "sigma_eff",
        "mu_shift_from_dx",
        "PC1",
        "PC2",
        *scaffold_columns,
    ]
    require_columns(sample_table, sample_columns, context="Sample dynamic table")

    output = interval_table[
        interval_table["interval_class"].astype(str) == str(interval_value)
    ].copy()
    if output.empty:
        raise ValueError(f"No {interval_value!r} interval records were found.")

    jump_subset = jump_table[
        ["patient_id", "sample_start", "sample_end", "jump_score"]
    ].drop_duplicates()
    output = output.merge(
        jump_subset,
        on=["patient_id", "sample_start", "sample_end"],
        how="left",
        validate="one_to_one",
    )

    sample_subset = sample_table[sample_columns].drop_duplicates("sample_id").copy()
    start_map = sample_subset.rename(
        columns={
            column: f"{column}_start"
            for column in sample_columns
            if column != "sample_id"
        }
    )
    end_map = sample_subset.rename(
        columns={
            column: f"{column}_end"
            for column in sample_columns
            if column != "sample_id"
        }
    )

    output = output.merge(
        start_map,
        left_on="sample_start",
        right_on="sample_id",
        how="left",
        validate="many_to_one",
    ).drop(columns=["sample_id"])
    output = output.merge(
        end_map,
        left_on="sample_end",
        right_on="sample_id",
        how="left",
        validate="many_to_one",
    ).drop(columns=["sample_id"])

    output["transition_label"] = (
        output["branch_start"].astype(str)
        + " -> "
        + output["branch_end"].astype(str)
    )
    output["transition_class"] = np.where(
        output["branch_switch"].astype(int) == 1,
        "Branch-switching",
        "Branch-continuous",
    )

    if "tail_flag_dx_rel_q90" in output.columns:
        output["tail_flag_dx_rel_q90"] = output[
            "tail_flag_dx_rel_q90"
        ].astype(bool)
    else:
        q90 = float(
            np.nanquantile(
                pd.to_numeric(output["displacement_hd"], errors="coerce"),
                0.90,
            )
        )
        output["tail_threshold_dx_rel_q90"] = q90
        # Inclusive fallback is intentionally preserved from the legacy Figure 5
        # table builder. Accepted Stage 1 inputs already carry the strict flag.
        output["tail_flag_dx_rel_q90"] = (
            pd.to_numeric(output["displacement_hd"], errors="coerce") >= q90
        )

    front = [
        "patient_id",
        "interval_class",
        "sample_start",
        "sample_end",
        "branch_start",
        "branch_end",
        "branch_switch",
        "transition_label",
        "transition_class",
        "displacement_hd",
        "jump_score",
        "tail_flag_dx_rel_q90",
        "ecotype_label_start",
        "ecotype_label_end",
        "theta_eff_start",
        "theta_eff_end",
        "sigma_eff_start",
        "sigma_eff_end",
        "mu_shift_from_dx_start",
        "mu_shift_from_dx_end",
        "PC1_start",
        "PC2_start",
        "PC1_end",
        "PC2_end",
    ]
    remaining = [column for column in output.columns if column not in front]
    return output[front + remaining]


def build_branch_ecology_summary(
    sample_table: pd.DataFrame,
    *,
    branch_order: Sequence[str],
    main_sample_column: str = "is_main_analysis_sample",
) -> pd.DataFrame:
    """Branch-by-ecotype sample composition for accepted analysis samples."""
    require_columns(
        sample_table,
        [
            main_sample_column,
            "branch_id_dominant",
            "ecotype_label",
            "PC1",
            "PC2",
            "theta_eff",
            "sigma_eff",
            "mu_shift_from_dx",
        ],
        context="Sample dynamic table",
    )
    selected = sample_table[sample_table[main_sample_column] == True].copy()  # noqa: E712
    selected = selected[selected["branch_id_dominant"].notna()].copy()

    branch_totals = (
        selected.groupby("branch_id_dominant", observed=False)
        .size()
        .rename("branch_total_samples")
        .reset_index()
    )
    ecology = (
        selected.groupby(
            ["branch_id_dominant", "ecotype_label"], observed=False
        )
        .size()
        .rename("n_samples")
        .reset_index()
    )
    ecology = ecology.merge(branch_totals, on="branch_id_dominant", how="left")
    ecology["fraction_within_branch"] = (
        ecology["n_samples"] / ecology["branch_total_samples"]
    )

    branch_summary = (
        selected.groupby("branch_id_dominant", observed=False)[
            ["PC1", "PC2", "theta_eff", "sigma_eff", "mu_shift_from_dx"]
        ]
        .mean()
        .reset_index()
        .rename(
            columns={
                "PC1": "PC1_mean",
                "PC2": "PC2_mean",
                "theta_eff": "theta_eff_mean",
                "sigma_eff": "sigma_eff_mean",
                "mu_shift_from_dx": "mu_shift_from_dx_mean",
            }
        )
    )
    ecology = ecology.merge(branch_summary, on="branch_id_dominant", how="left")

    # The second lexical sort is retained because it is part of the validated
    # output order, even though it supersedes the declared-order helper here.
    ecology = sort_by_declared_order(
        ecology, "branch_id_dominant", branch_order
    ).sort_values(
        ["branch_id_dominant", "fraction_within_branch", "ecotype_label"],
        ascending=[True, False, True],
    )
    return ecology


def build_branch_scaffold_program_summary(
    sample_table: pd.DataFrame,
    *,
    scaffold_columns: Sequence[str],
    branch_order: Sequence[str],
    main_sample_column: str = "is_main_analysis_sample",
) -> pd.DataFrame:
    """Branch-level scaffold and effective-dynamic means and z-scores."""
    scaffold_columns = tuple(str(column) for column in scaffold_columns)
    aggregate_columns = [
        *scaffold_columns,
        "theta_eff",
        "sigma_eff",
        "mu_shift_from_dx",
    ]
    require_columns(
        sample_table,
        [main_sample_column, "branch_id_dominant", *aggregate_columns],
        context="Sample dynamic table",
    )
    selected = sample_table[sample_table[main_sample_column] == True].copy()  # noqa: E712
    selected = selected[selected["branch_id_dominant"].notna()].copy()

    summary = (
        selected.groupby("branch_id_dominant", observed=False)[aggregate_columns]
        .mean()
        .reset_index()
    )
    counts = (
        selected.groupby("branch_id_dominant", observed=False)
        .size()
        .rename("n_samples")
        .reset_index()
    )
    summary = summary.merge(counts, on="branch_id_dominant", how="left")
    summary = summary.rename(
        columns={column: f"{column}_mean" for column in aggregate_columns}
    )

    for column in scaffold_columns:
        summary[f"{column}_z"] = zscore_series(summary[f"{column}_mean"])
    for column in (
        "theta_eff_mean",
        "sigma_eff_mean",
        "mu_shift_from_dx_mean",
    ):
        summary[f"{column}_z"] = zscore_series(summary[column])

    return sort_by_declared_order(summary, "branch_id_dominant", branch_order)


def build_branch_escape_risk_summary(
    transition_table: pd.DataFrame,
    *,
    branch_order: Sequence[str],
) -> pd.DataFrame:
    """Summarize switching, displacement, and jump scores by start branch."""
    require_columns(
        transition_table,
        [
            "patient_id",
            "branch_start",
            "branch_switch",
            "jump_score",
            "displacement_hd",
            "tail_flag_dx_rel_q90",
        ],
        context="Transition table",
    )
    output = (
        transition_table.groupby("branch_start", observed=False)
        .agg(
            n_intervals=("patient_id", "size"),
            n_switch=(
                "branch_switch",
                lambda values: int(
                    np.sum(
                        pd.to_numeric(values, errors="coerce")
                        .fillna(0)
                        .astype(int)
                        == 1
                    )
                ),
            ),
            n_stable=(
                "branch_switch",
                lambda values: int(
                    np.sum(
                        pd.to_numeric(values, errors="coerce")
                        .fillna(0)
                        .astype(int)
                        == 0
                    )
                ),
            ),
            switch_fraction=(
                "branch_switch",
                lambda values: float(
                    np.mean(
                        pd.to_numeric(values, errors="coerce")
                        .fillna(0)
                        .astype(int)
                        == 1
                    )
                ),
            ),
            mean_jump_score=(
                "jump_score",
                lambda values: float(
                    np.nanmean(pd.to_numeric(values, errors="coerce"))
                ),
            ),
            median_jump_score=(
                "jump_score",
                lambda values: float(
                    np.nanmedian(pd.to_numeric(values, errors="coerce"))
                ),
            ),
            mean_displacement_hd=(
                "displacement_hd",
                lambda values: float(
                    np.nanmean(pd.to_numeric(values, errors="coerce"))
                ),
            ),
            median_displacement_hd=(
                "displacement_hd",
                lambda values: float(
                    np.nanmedian(pd.to_numeric(values, errors="coerce"))
                ),
            ),
            tail_fraction_dx_rel_q90=(
                "tail_flag_dx_rel_q90",
                lambda values: float(np.mean(pd.Series(values).astype(bool))),
            ),
        )
        .reset_index()
        .rename(columns={"branch_start": "branch_id_start"})
    )
    output["mean_jump_score_z"] = zscore_series(output["mean_jump_score"])
    output["mean_displacement_hd_z"] = zscore_series(
        output["mean_displacement_hd"]
    )
    return sort_by_declared_order(output, "branch_id_start", branch_order)


def build_branch_stats_summary(
    transition_table: pd.DataFrame,
    ecology_summary: pd.DataFrame,
    escape_risk_summary: pd.DataFrame,
) -> pd.DataFrame:
    """Build the compact mixed-type Figure 5 manuscript summary table."""
    rows: list[dict[str, Any]] = []

    transition_counts = (
        transition_table.groupby(["branch_start", "branch_end"], observed=False)
        .size()
        .rename("count")
        .reset_index()
    )
    for _, row in transition_counts.iterrows():
        rows.append(
            {
                "section": "transition_count",
                "item": f"{row['branch_start']} -> {row['branch_end']}",
                "value": float(row["count"]),
            }
        )

    top_ecology = (
        ecology_summary.sort_values(
            ["branch_id_dominant", "fraction_within_branch"],
            ascending=[True, False],
        )
        .groupby("branch_id_dominant", observed=False)
        .head(1)
    )
    for _, row in top_ecology.iterrows():
        rows.append(
            {
                "section": "dominant_ecotype_by_branch",
                "item": f"{row['branch_id_dominant']}",
                "value": (
                    f"{row['ecotype_label']} "
                    f"({row['fraction_within_branch']:.3f})"
                ),
            }
        )

    for _, row in escape_risk_summary.iterrows():
        rows.append(
            {
                "section": "branch_escape_risk",
                "item": f"{row['branch_id_start']}",
                "value": (
                    f"mean_jump={row['mean_jump_score']:.3f}; "
                    f"switch_frac={row['switch_fraction']:.3f}"
                ),
            }
        )
    return pd.DataFrame(rows)


def build_branch_summary_artifacts(
    interval_table: pd.DataFrame,
    jump_table: pd.DataFrame,
    sample_table: pd.DataFrame,
    *,
    scaffold_columns: Sequence[str],
    branch_order: Sequence[str],
    interval_value: str = "DX_to_REL",
) -> BranchSummaryArtifacts:
    """Build all validated frozen-scaffold branch summary tables."""
    transition = build_branch_transition_table(
        interval_table,
        jump_table,
        sample_table,
        scaffold_columns=scaffold_columns,
        interval_value=interval_value,
    )
    ecology = build_branch_ecology_summary(
        sample_table,
        branch_order=branch_order,
    )
    program = build_branch_scaffold_program_summary(
        sample_table,
        scaffold_columns=scaffold_columns,
        branch_order=branch_order,
    )
    risk = build_branch_escape_risk_summary(
        transition,
        branch_order=branch_order,
    )
    stats = build_branch_stats_summary(transition, ecology, risk)
    return BranchSummaryArtifacts(
        transition_table=transition,
        ecology_summary=ecology,
        program_summary=program,
        escape_risk_summary=risk,
        stats_summary=stats,
    )


# ---------------------------------------------------------------------------
# Threshold-dependent B1--B3 projection sensitivity
# ---------------------------------------------------------------------------


def add_threshold_branch_assignments(
    table: pd.DataFrame,
    *,
    thresholds: Sequence[int],
    spec: ThresholdBranchSpec = ThresholdBranchSpec(),
) -> pd.DataFrame:
    """Recompute eligibility and nearest projected branch at each threshold."""
    threshold_values = tuple(int(value) for value in thresholds)
    if not threshold_values:
        raise ValueError("At least one threshold is required.")
    if any(value < 0 for value in threshold_values):
        raise ValueError("Thresholds must be non-negative.")
    if len(set(threshold_values)) != len(threshold_values):
        raise ValueError("Thresholds must be unique.")

    required = [
        spec.sample_column,
        spec.patient_column,
        spec.sample_id_column,
        spec.timepoint_column,
        spec.time_index_column,
        spec.malignant_cells_column,
        spec.projection_eligible_column,
        *spec.branch_distance_columns,
        *spec.state_columns,
    ]
    require_columns(table, required, context="Longitudinal branch projection table")

    output = table.copy()
    numeric_columns = [
        *spec.state_columns,
        *spec.branch_distance_columns,
        spec.malignant_cells_column,
    ]
    for column in numeric_columns:
        output[column] = pd.to_numeric(output[column], errors="coerce")

    distance_to_label = dict(
        zip(spec.branch_distance_columns, spec.branch_labels, strict=True)
    )
    for threshold in threshold_values:
        eligible_column = f"eligible_ge{threshold}"
        branch_column = f"branch_ge{threshold}"
        output[eligible_column] = (
            output[spec.malignant_cells_column].fillna(0) >= threshold
        ) & (~output[list(spec.state_columns)].isna().any(axis=1)) & (
            ~output[list(spec.branch_distance_columns)].isna().any(axis=1)
        )
        output[branch_column] = pd.NA
        nearest_distance_column = output.loc[
            output[eligible_column], list(spec.branch_distance_columns)
        ].idxmin(axis=1)
        output.loc[output[eligible_column], branch_column] = (
            nearest_distance_column.map(distance_to_label)
        )
    return output


def build_threshold_branch_counts(
    projected_table: pd.DataFrame,
    *,
    thresholds: Sequence[int],
    spec: ThresholdBranchSpec = ThresholdBranchSpec(),
) -> pd.DataFrame:
    """Count threshold-eligible projected branches by timepoint."""
    rows: list[dict[str, Any]] = []
    timepoints = sorted(
        projected_table[spec.timepoint_column].dropna().unique()
    )
    for threshold in (int(value) for value in thresholds):
        branch_column = f"branch_ge{threshold}"
        eligible_column = f"eligible_ge{threshold}"
        require_columns(
            projected_table,
            [branch_column, eligible_column, spec.timepoint_column],
            context="Threshold-projected table",
        )
        for timepoint in timepoints:
            subset = projected_table[
                projected_table[spec.timepoint_column] == timepoint
            ]
            record: dict[str, Any] = {
                "threshold": threshold,
                "timepoint": timepoint,
                "n_total_samples": int(len(subset)),
                "n_eligible": int(subset[eligible_column].sum()),
            }
            for label in spec.branch_labels:
                record[label] = int((subset[branch_column] == label).sum())
            record["NA"] = int(subset[branch_column].isna().sum())
            rows.append(record)
    return pd.DataFrame(rows)


def build_threshold_patient_transition_tables(
    projected_table: pd.DataFrame,
    *,
    thresholds: Sequence[int],
    spec: ThresholdBranchSpec = ThresholdBranchSpec(),
) -> tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame]:
    """Build patient, transition-matrix, and switch-rate threshold tables."""
    patient_rows: list[pd.DataFrame] = []
    transition_rows: list[dict[str, Any]] = []
    switch_rows: list[dict[str, Any]] = []

    for threshold in (int(value) for value in thresholds):
        branch_column = f"branch_ge{threshold}"
        eligible_column = f"eligible_ge{threshold}"
        require_columns(
            projected_table,
            [
                spec.sample_column,
                spec.patient_column,
                spec.sample_id_column,
                spec.timepoint_column,
                spec.time_index_column,
                spec.malignant_cells_column,
                eligible_column,
                branch_column,
            ],
            context="Threshold-projected table",
        )

        aggregate: dict[str, Any] = {spec.patient_column: first_nonmissing}
        for column in spec.metadata_columns:
            if column in projected_table.columns:
                aggregate[column] = first_nonmissing
        aggregate.update(
            {
                spec.malignant_cells_column: "first",
                eligible_column: "first",
                branch_column: first_nonmissing,
            }
        )

        patient_timepoint = (
            projected_table.sort_values(
                [
                    spec.sample_column,
                    spec.time_index_column,
                    spec.sample_id_column,
                ]
            )
            .groupby(
                [spec.sample_column, spec.timepoint_column],
                as_index=False,
                observed=False,
            )
            .agg(aggregate)
        )

        wide = patient_timepoint.pivot(
            index=spec.sample_column,
            columns=spec.timepoint_column,
            values=branch_column,
        )
        wide.columns = [f"{column}_branch_ge{threshold}" for column in wide.columns]
        wide = wide.reset_index()

        meta_aggregate: dict[str, Any] = {spec.patient_column: first_nonmissing}
        for column in spec.metadata_columns:
            if column in patient_timepoint.columns:
                meta_aggregate[column] = first_nonmissing
        metadata = (
            patient_timepoint.groupby(
                spec.sample_column,
                as_index=False,
                observed=False,
            )
            .agg(meta_aggregate)
        )

        patient_table = metadata.merge(
            wide,
            on=spec.sample_column,
            how="left",
        )
        patient_table["threshold"] = threshold

        diagnosis_column = f"{spec.diagnosis_timepoint}_branch_ge{threshold}"
        relapse_column = f"{spec.relapse_timepoint}_branch_ge{threshold}"
        if (
            diagnosis_column in patient_table.columns
            and relapse_column in patient_table.columns
        ):
            patient_table["dx_rel_pair_available"] = (
                patient_table[diagnosis_column].notna()
                & patient_table[relapse_column].notna()
            )
            patient_table["dx_to_rel_switch"] = np.where(
                patient_table["dx_rel_pair_available"],
                patient_table[diagnosis_column] != patient_table[relapse_column],
                pd.NA,
            )
        else:
            patient_table["dx_rel_pair_available"] = False
            patient_table["dx_to_rel_switch"] = pd.NA
        patient_rows.append(patient_table)

        if (
            diagnosis_column in patient_table.columns
            and relapse_column in patient_table.columns
        ):
            pair = patient_table.loc[
                patient_table["dx_rel_pair_available"],
                [diagnosis_column, relapse_column],
            ].copy()
            if len(pair) > 0:
                transition = pd.crosstab(
                    pair[diagnosis_column], pair[relapse_column], dropna=False
                )
                for diagnosis_branch in spec.branch_labels:
                    for relapse_branch in spec.branch_labels:
                        transition_rows.append(
                            {
                                "threshold": threshold,
                                "dx_branch": diagnosis_branch,
                                "rel_branch": relapse_branch,
                                "count": int(
                                    transition.loc[
                                        diagnosis_branch, relapse_branch
                                    ]
                                )
                                if diagnosis_branch in transition.index
                                and relapse_branch in transition.columns
                                else 0,
                            }
                        )
                n_pairs = int(len(pair))
                n_switch = int(
                    (pair[diagnosis_column] != pair[relapse_column]).sum()
                )
                switch_rows.append(
                    {
                        "threshold": threshold,
                        "n_dx_rel_pairs": n_pairs,
                        "n_switch": n_switch,
                        "n_stable": n_pairs - n_switch,
                        "switch_rate": n_switch / n_pairs if n_pairs > 0 else np.nan,
                    }
                )
            else:
                switch_rows.append(
                    {
                        "threshold": threshold,
                        "n_dx_rel_pairs": 0,
                        "n_switch": 0,
                        "n_stable": 0,
                        "switch_rate": np.nan,
                    }
                )

    if not patient_rows:
        raise ValueError("No threshold-specific patient tables were generated.")
    patient_output = pd.concat(patient_rows, ignore_index=True)
    transition_output = pd.DataFrame(transition_rows)
    switch_output = pd.DataFrame(switch_rows).sort_values("threshold")
    return patient_output, transition_output, switch_output


def build_threshold_summary_text(
    counts_table: pd.DataFrame,
    transition_table: pd.DataFrame,
    patient_table: pd.DataFrame,
    switch_table: pd.DataFrame,
    *,
    thresholds: Sequence[int],
    spec: ThresholdBranchSpec = ThresholdBranchSpec(),
    heading: str = "GSE235063 transition summary and threshold sensitivity",
) -> str:
    """Create the validated plain-text threshold sensitivity report."""
    lines: list[str] = [heading, "=" * 70, ""]
    for threshold in (int(value) for value in thresholds):
        lines.append(f"Threshold >= {threshold} malignant cells")
        lines.append("-" * 40)

        count_subset = counts_table[counts_table["threshold"] == threshold].copy()
        lines.append("Branch counts by timepoint:")
        lines.append(count_subset.to_string(index=False))
        lines.append("")

        switch_subset = switch_table[switch_table["threshold"] == threshold]
        if len(switch_subset) > 0:
            lines.append("DX -> REL switch summary:")
            lines.append(switch_subset.to_string(index=False))
            lines.append("")

        transition_subset = transition_table[
            transition_table["threshold"] == threshold
        ].copy()
        if len(transition_subset) > 0:
            matrix = (
                transition_subset.pivot(
                    index="dx_branch",
                    columns="rel_branch",
                    values="count",
                )
                .fillna(0)
                .astype(int)
            )
            lines.append("DX -> REL transition matrix:")
            lines.append(matrix.to_string())
            lines.append("")

        patient_subset = patient_table[
            patient_table["threshold"] == threshold
        ].copy()
        keep_columns = [
            column
            for column in [
                spec.sample_column,
                spec.patient_column,
                "Treatment_Outcome",
                "Subgroup",
                f"{spec.diagnosis_timepoint}_branch_ge{threshold}",
                f"{spec.remission_timepoint}_branch_ge{threshold}",
                f"{spec.relapse_timepoint}_branch_ge{threshold}",
                "dx_rel_pair_available",
                "dx_to_rel_switch",
            ]
            if column in patient_subset.columns
        ]
        lines.append("Patient-level branch table:")
        lines.append(
            patient_subset[keep_columns]
            .sort_values(spec.sample_column)
            .to_string(index=False)
        )
        lines.append("")
    return "\n".join(lines)


def run_threshold_sensitivity(
    table: pd.DataFrame,
    *,
    thresholds: Sequence[int],
    spec: ThresholdBranchSpec = ThresholdBranchSpec(),
    heading: str = "GSE235063 transition summary and threshold sensitivity",
) -> ThresholdSensitivityArtifacts:
    """Run the complete threshold-dependent branch projection workflow."""
    projected = add_threshold_branch_assignments(
        table,
        thresholds=thresholds,
        spec=spec,
    )
    counts = build_threshold_branch_counts(
        projected,
        thresholds=thresholds,
        spec=spec,
    )
    patient, transitions, switches = build_threshold_patient_transition_tables(
        projected,
        thresholds=thresholds,
        spec=spec,
    )
    text = build_threshold_summary_text(
        counts,
        transitions,
        patient,
        switches,
        thresholds=thresholds,
        spec=spec,
        heading=heading,
    )
    return ThresholdSensitivityArtifacts(
        projected_table=projected,
        counts_by_timepoint=counts,
        transition_summary=transitions,
        patient_table=patient,
        switch_rates=switches,
        summary_text=text,
    )
